// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOlzXGHDSyix6igA7RHZ1xbaGsPfvwHpc',
    appId: '1:765585755938:web:52ffdab3e16ac768d69f7b',
    messagingSenderId: '765585755938',
    projectId: 'app-flutter-ce680',
    authDomain: 'app-flutter-ce680.firebaseapp.com',
    storageBucket: 'app-flutter-ce680.firebasestorage.app',
    measurementId: 'G-8FWW80VMT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWWZ8lrdDS9Kike4Ssd1O3wO2G2lJoEk',
    appId: '1:765585755938:android:9091ad237105b5c9d69f7b',
    messagingSenderId: '765585755938',
    projectId: 'app-flutter-ce680',
    storageBucket: 'app-flutter-ce680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3q4IBJZCJAWJAKG44yiTZdcFcY_ZjQjM',
    appId: '1:765585755938:ios:48dd91c538cf3526d69f7b',
    messagingSenderId: '765585755938',
    projectId: 'app-flutter-ce680',
    storageBucket: 'app-flutter-ce680.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3q4IBJZCJAWJAKG44yiTZdcFcY_ZjQjM',
    appId: '1:765585755938:ios:48dd91c538cf3526d69f7b',
    messagingSenderId: '765585755938',
    projectId: 'app-flutter-ce680',
    storageBucket: 'app-flutter-ce680.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOlzXGHDSyix6igA7RHZ1xbaGsPfvwHpc',
    appId: '1:765585755938:web:4bca83de8527eb70d69f7b',
    messagingSenderId: '765585755938',
    projectId: 'app-flutter-ce680',
    authDomain: 'app-flutter-ce680.firebaseapp.com',
    storageBucket: 'app-flutter-ce680.firebasestorage.app',
    measurementId: 'G-PXWYDHH8DJ',
  );

}