// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAnyl3kwWgcXUWScWKUK4HGVjvUMbXqo',
    appId: '1:353025530362:web:86cca1d1b8c25b76e22c43',
    messagingSenderId: '353025530362',
    projectId: 'analisador-texto-luiz-cd73f',
    authDomain: 'analisador-texto-luiz-cd73f.firebaseapp.com',
    storageBucket: 'analisador-texto-luiz-cd73f.firebasestorage.app',
    measurementId: 'G-Z6Q4H7JLWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYFga83j1VyQmNqB8w1Uw1RxIo6d3wzI',
    appId: '1:353025530362:android:838cd39d000d631fe22c43',
    messagingSenderId: '353025530362',
    projectId: 'analisador-texto-luiz-cd73f',
    storageBucket: 'analisador-texto-luiz-cd73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZY5eIIFBUKRI_p7-usiTiSNG7dC03rDc',
    appId: '1:353025530362:ios:ac9a1685a0c49108e22c43',
    messagingSenderId: '353025530362',
    projectId: 'analisador-texto-luiz-cd73f',
    storageBucket: 'analisador-texto-luiz-cd73f.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZY5eIIFBUKRI_p7-usiTiSNG7dC03rDc',
    appId: '1:353025530362:ios:ac9a1685a0c49108e22c43',
    messagingSenderId: '353025530362',
    projectId: 'analisador-texto-luiz-cd73f',
    storageBucket: 'analisador-texto-luiz-cd73f.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAnyl3kwWgcXUWScWKUK4HGVjvUMbXqo',
    appId: '1:353025530362:web:3c2af42bfc63c8c5e22c43',
    messagingSenderId: '353025530362',
    projectId: 'analisador-texto-luiz-cd73f',
    authDomain: 'analisador-texto-luiz-cd73f.firebaseapp.com',
    storageBucket: 'analisador-texto-luiz-cd73f.firebasestorage.app',
    measurementId: 'G-N6XKSQN3CP',
  );

}